Add ci to build and upload doc

diff --git a/.github/workflows/build_docs.yml b/.github/workflows/build_docs.yml
--- a/.github/workflows/build_docs.yml
+++ b/.github/workflows/build_docs.yml
@@ -61,14 +61,16 @@ jobs:
             echo "flink_alias=stable" >> ${GITHUB_ENV}
           fi
 
-      - name: Setup Hugo
-        uses: peaceiris/actions-hugo@v2
-        with:
-          hugo-version: '0.119.0'
-          extended: true
-
       - name: Build documentation
         run: |
+          HUGO_REPO=https://github.com/gohugoio/hugo/releases/download/v0.110.0/hugo_extended_0.110.0_Linux-64bit.tar.gz
+          HUGO_ARTIFACT=hugo_extended_0.110.0_Linux-64bit.tar.gz
+          if ! curl --fail -OL $HUGO_REPO ; then
+          echo "Failed to download Hugo binary"
+          exit 1
+          fi
+          tar -zxvf $HUGO_ARTIFACT -C /usr/local/bin
+  
           git submodule update --init --recursive
           
           hugo mod get -u
